Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select Environment Size (S,M,L)
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    Default: r1111111ahul
    NoEcho: true
  TestString:
    Type: String
    Default: test9
Mappings:
  RegionMap:
    ap-south-1:
      "AMALINUX" : "ami-0d2692b6acea72ee6" # AMALINUX SEP 2016
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    MEDIUM:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    LARGE:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
Resources:
  # DB:
  #   Type: "AWS::RDS::DBInstance"
  #   Properties:
  #     AllocatedStorage: 5
  #     StorageType: gp2
  #     DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] # Dynamic mapping + Pseudo Parameter
  #     DBName: !Ref DatabaseName
  #     Engine: MySQL
  #     MasterUsername: !Ref DatabaseUser
  #     MasterUserPassword: !Ref DatabasePassword
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      KeyName: Rahul_Mumbai
      SecurityGroups:
        - !ImportValue WBSecurityGroup
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y aws-cfn-bootstrap # good practice - always do this.
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
            yum -y update
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          wordpress:
            - "configure_cfn"
            - "install_wordpress"
            - "install_node"
            # - "config_wordpress"
        configure_cfn:
          files:
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets wordpress --region ${AWS::Region}
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                verbose=true
                interval=5
              mode: "000400"
              owner: root
              group: root
            /var/www/html/index2.html:
              content: !Ref TestString
            /tmp/subscript.sh:
              content: !Sub |
                  echo "rahul" > test.txt
                  echo "Setting up NodeJS Environment"
                  curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | sudo bash
                  # sleep 30;
                  echo 'export NVM_DIR="/root/.nvm"' >> /root/.bashrc
                  # . /home/ec2-user/.bashrc
                  # source ~/.bashrc 
                  echo "type"
                  id -a 
                  echo $NVM_DIR
                  # echo $NVM_DIR
                  # curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | sudo bash
                  # echo [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> /home/ec2-user/.bashrc
                  # echo "cat"
                  # if [ ! -f $NVM_DIR/nvm.sh ]; then
                  #     echo "File not found!"
                  # fi
                  # Dot source the files to ensure that variables are available within the current shell
                  # sleep 1; . /home/ec2-user/.nvm/nvm.sh
                  
                  # # Install NVM, NPM, Node.JS & Grunt
                  # nvm install v12.8.0
                  # nvm alias default v12.8.0
                  # nvm use v12.8.0
                  
                  # curl -o- -L https://yarnpkg.com/install.sh | bash
                  # export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" 
                  # echo "rahul" > rahul.txt
              mode: "777"
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/cfn/cfn-hup.conf"
                  - "/etc/cfn/hooks.d/cfn-auto-reloader.conf"
                  - "/tmp/subscript.sh"
        install_wordpress:
          packages:
            yum:
              httpd: []
          # sources:
          #   /var/www/html: "http://wordpress.org/latest.tar.gz"
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
        install_node:
          commands:
            01_config:
              cwd: "~"
              # test: test ! -e /tmp/subscript.sh
              command:  sh /tmp/subscript.sh
            # 02_loadAgain:
            #   cwd: "~"
            #   command: . /home/ec2-user/.nvm/nvm.sh
            # 03_inject_dbname:
            #   cwd: "/var/www/html/wordpress"
            #   command: !Sub |
            #     sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            # 04_inject_dbuser:
            #   cwd: "/var/www/html/wordpress"
            #   command: !Sub |
            #     sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            # 05_inject_dbpassword:
            #   cwd: "/var/www/html/wordpress"
            #   command: !Sub |
            #     sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  # S3:
  #   Type: "AWS::S3::Bucket"
