Parameters:
  KeyName:
      Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
      Type: AWS::EC2::KeyPair::KeyName
      ConstraintDescription: must be the name of an existing EC2 KeyPair.