Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH access via port 22
      GroupName: TCP SecurityGroup CF
      Tags: 
        -
          Key: "SecurityGroupType"
          Value: "TCP"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow connections from specified CIDR ranges
      GroupName: HTTP SecurityGroup CF
      Tags: 
        -
          Key: "SecurityGroupType"
          Value: "HTTP"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp

Outputs:
  LogicalID:
    Description: Information about the value
    Value:
    Export: 
      Name: