Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH access via port 22
      GroupName: TCP GroupName
      Tags: 
        -
          Key: "SecurityGroup"
          Value: "TCP"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: allow connections from specified CIDR ranges
      GroupName: HTTP GroupName
      Tags: 
        -
          Key: "SecurityGroup"
          Value: "HTTP"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp